### ISSUE TITLE
Update lodash dependency to >=4.17.5

### ISSUE THREAD

**Issue by davidsneighbour** [dylang/grunt-prompt#50]
`npm install` bemoans two low severity vulnerabilities in connection with this package:

```npm audit``` returns:
                                                                                
```Some vulnerabilities require your attention to resolve 
Visit https://go.npm.me/audit-guide for additional guidance

Low           │ Prototype Pollution    
Package       │ lodash  
Patched in    │ >=4.17.5    
Dependency of │ grunt-prompt         
Path          │ grunt-prompt > inquirer > lodash      
More info     │ https://nodesecurity.io/advisories/577        

Low           │ Prototype Pollution     
Package       │ lodash             
Patched in    │ >=4.17.5           
Dependency of │ grunt-prompt    
Path          │ grunt-prompt > lodash       
More info     │ https://nodesecurity.io/advisories/577      

found 2 low severity vulnerabilities in 13285 scanned packages
  2 vulnerabilities require manual review. See the full report for details.
```

As the used version is at 3, I am not sure how much work is required to update this to 4.17.5?

**Comment by jeremykorb** [comment]
Curious if there is any active development on this package and if this can be looked at or any info provided on what it would take to bring the lodash dependency up to 4.17.5?

**Comment by nateplusplus** [comment]
Checking in on this again since it's been a year. Anyone have advice for a fix?

**Comment by davidsneighbour** [comment]
No need then [year end cleanup :)]

**Comment by piper1970** [comment]
This issue is still unresolved. https://github.com/dylang/grunt-prompt/issues/52
